dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0

compiler:
  evm_version: null
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'

dotenv: .env

networks:
  live:
    gas_limit: "1000000"
